### ISSUE TITLE
Support for tor apt-transport

### ISSUE THREAD

**Issue by xSmurf** [nthykier/apt-file#1]
apt-file currently fails if source.list entries are configured with tor+http(s) apt transport.

```
W: Don't know how to handle tor+http
W: Don't know how to handle tor+https
E: No valid sources in /etc/apt/sources.list
```

**Comment by nthykier** [comment]
Hi,

Support for tor+http(s) was added in apt-file/3 (uploaded to Debian unstable today). :)

It is not available in Debian stable (jessie) and is unlikely to be backported, since it requires some extra features in APT itself (notably, you need at least APT 1.1 and probably APT 1.2).

**Comment by xSmurf** [comment]
I should have checked, it wasn't in testing and I made the wrongful assumption that things weren't moving much. Should have checked the commit log, my bad!

Thanks a bunch :)
