### ISSUE TITLE
`apt-file` has no results, is that due to missing `Contents` files?

### ISSUE THREAD

**Issue by drmuey** [nthykier/apt-file#2]
Hello,

From what I can tell fromt he internets `apt-file` is not working for us because our repos do not have a Contents file.

I created [this OBS issue](https://github.com/openSUSE/open-build-service/issues/10952) to see about having it built in the pipeline.

Can you confirm that the reason `apt-file` would return not results (exits 1) is because the source is missing the `Contents` file? In other words if there was a valid Contents[.gz] `apt-file` would find the info no problem.

If so then [this OBS issue](https://github.com/openSUSE/open-build-service/issues/10952) is valid, if not it needs adjusted/closed and something else done.

Thanks!

**Comment by nthykier** [comment]
Hi,

Short answer: You are most likely right.

The longer one:
When "apt-file search foo" exits with 1, then it means that apt-file had Contents files to search but did find a match for `foo`. This can happen for two obvious reasons:

 1) The string `foo` is not in any package from any of your apt sources.
 2) The string `foo` is present a package from in one of your apt sources, but only in apt sources that do not have Contents files.

(note that if none of your apt sources have Contents files, then you get a different error)

Sadly, apt-file is somewhat unhelpful at telling the two a part.  However, given a quick read of the OBS issue, the fact that `dpkg -S foo` works after installing a package from the OBS mirror but `apt-file search foo` does smell like missing Contents files.

**Additional debugging aid:**

You can use the following command to tell which mirror locations that you have Contents files for (as of last `apt update`).
```
(apt-get indextargets --format '$(URI)' 'Created-by: Contents-deb' ; apt-get indextargets --format '$(URI)' 'Created-by: Contents-deb-legacy')
```

If that does not list any of the OBS URLs  but it lists other URLs, then it is most likely that OBS does not provide any Contents files.

For reference, you can compare the output of the command above with this, which is a good approximation for which servers you might expect to see:
```
apt-get indextargets --format '$(URI)' 'Created-by: Packages'
```

Ideally, the OBS server will be listed in the output of both commands.  But likely you will only see it in the output of the `'Created-by: Packages'`-case.

(Note that it is `apt-get` in this case and that `apt-get indextargets` may require an `apt update` if you change sources or apt configuration)

**Comment by drmuey** [comment]
Awesome, thank you for taking the time to give us that info @nthykier  👍

That was it exactly:

* `apt-get indextargets |grep -E "Created-By:.*Contents"` ➜ on this box it is `Contents-deb-legacy`
* `apt-get indextargets --format '$(URI)' 'Created-by: Contents-deb-legacy' ➜ 
   * nova.clouds.archive.ubuntu.com URls
   * security.ubuntu.com URLs
   * no OBS repo URL
* `apt-get indextargets --format '$(URI)' 'Created-by: Packages'` ➜ all output
   * nova.clouds.archive.ubuntu.com URls
   * security.ubuntu.com URLs
   * and my OBS repo URL
