### ISSUE TITLE
50apt-file.conf using wrong commenting syntax

### ISSUE THREAD

**Issue by Jason-Lee-Quinn** [nthykier/apt-file#4]
Hi, the file

50apt-file.conf

is using both double and single hashes for comments but APT uses C-style commenting for its configuration files. So either // or the /* abcde */ style commenting should be used.

This can cause some tools to fail. For example when a "cupt why" command is given to the cupt package manager, it spits out

E: syntax error: line 1, character 1: expected: clear directive ('#clear') or option name (letters, numbers, slashes, points, dashes, double colons allowed)
E: unable to parse the config file '//etc/apt/apt.conf.d/50apt-file.conf'
W: skipped the configuration file '//etc/apt/apt.conf.d/50apt-file.conf'

All the file's comments should be converted to C-style as per "man 5 apt.conf".

**Comment by nthykier** [comment]
`man 5 apt.conf` says that `#` is also a comment:

```
Lines starting with # are also treated as comments.
```
(I am aware there is a "special" directive in the form of `#clear` which is not a comment - but everything else starting with `# ` is)

As I understand it, you have a bug in cupt rather than in apt-file (or maybe in the documentation of `apt.conf` and `apt-file`).

**Comment by Jason-Lee-Quinn** [comment]
It appears you are correct. The current version of APT's man page includes the documentation you quote. (This line was not in my apt conf documentation so I missed it.)

https://github.com/Debian/apt/blob/edffb0ae26935d948ffeb3be229fdcf37d2a1ee1/doc/apt.conf.5.xml

So, as you suggest, it's either cupt needing update, or it's a slight versioning incompatibility bug among packages in Debian Bullseye.

I suppose this is "not a bug" and will close. Thank you for your time.
